### ISSUE TITLE
What threshold number should be used if we need the results to be as reliable as possible

### ISSUE THREAD

**Issue by tinyfallen** [screamer/miteFinder#5]
Hi dear developer,

Thanks for your great scripts! 

I have try some thresholds from default 0.2 to 0.9, and the number of MITEs varied from thousand to several.  So I would like to know your suggestion about the threshold to be used if I need the results to be as reliable as possible with the balance bwteen MITEs' count and accuracy?

**Comment by jhu99** [comment]
Thanks for your feedback. 
The default threshold is a simple setting for a quick start. It doesn't mean that we recommend it as a gold standard. This parameter was designed as a user-defined one because the best choice is not fixed for all applications. It depends on your own input data.
Jialu

**Comment by tinyfallen** [comment]
> Thanks for your feedback. The default threshold is a simple setting for a quick start. It doesn't mean that we recommend it as a gold standard. This parameter was designed as a user-defined one because the best choice is not fixed for all applications. It depends on your own input data. Jialu

Thanks for your explantion! And I have some questions about the results. In the descriprion you said **m1 means the TIR is the imperfect inverted repeats and 4138 is the mismatch base**,  I would infer the m0 label representing a perfect inverted repeats, so what does the number in front of m0 mean? What if there are more than one bases mismatching? In other words, may I treat the sequences labelled with m0 as high confidence ones?

**Comment by jhu99** [comment]
> 

Sorry for the confusion. Here, m1 means that there is only one mismatch in the TIR, and the mismatch base is at 4138. The m0 label means that there is no mismatch in TIR (a perfect inverted repeat).  If there is no mismatch, you can just ignore the number in front of m0 (because it might be the start position of this mite or something else. Sorry, I forgot the exact meaning). So you are right. Normally, we treated the one with perfect TIR as one mite with a high confidence.

**Comment by tinyfallen** [comment]
Many thanks for your timely reply, it is very helpful!

Best~
