### ISSUE TITLE
Issue in detection

### ISSUE THREAD

**Issue by Ramkyeri** [screamer/miteFinder#7]
Dear Jialu Hu,
Greetings!
I am using miteFinder in Transposon Ulitimate, but it generates 0 KB resutls.
Then when I run it alone it generates 2.7 MB results of 2.Gb size.
could you give me some suggestions?

with kind regards

Ramky

**Comment by ZhangStudyHard** [comment]
Dear Ramky,
Thanks for your question!
I have the following three suggestions, I hope they can help you.
First, reinstall the environment. This tool is already a very complete tool, and it is also very convenient to use. After many tests, no problems were found.Second, use your data and run it strictly according to the tools in the tutorial provided by this tool, it may be because you have modified the data during the running process.Third, it may be that this tool does not work very well on your data. You can download public datasets available online to try.
Finally, if you still can't solve your problem, if you can, you can send us the data set by email, and we will run it on your data.My email is zhang17779696950@163.com.

with kind regards

HaoHuiZhang

**Comment by Ramkyeri** [comment]
Dear HaoHuiZhang, 
Greetings!
Many thanks for your kind reply.

This is the command that I used    `/bin/miteFinder -input sequence.fasta -output results.txt -pattern_scoring ./profile/pattern_scoring.txt -threshold 0.5`

I will update you the results.
with regards
Ramky
